services:
  checkinasn-api:
    container_name: checkinasn-api
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - psql
    networks:
      - my-network
    env_file:
      - ./.env 

  psql:
    container_name: psql
    image: postgres:16.4-alpine3.20
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432
    networks:
      - my-network

networks:
  my-network: